variable "KubeNodeType" {
  default = "m4.large"
}variable "KubeNodes" {
  default = "3"
}variable "Ingestion" {
  default = "None"
}variable "IngestionMaster" {
  default = "0"
}variable "IngestionWorker" {
  default = "0"
}variable "Compute" {
  default = "spark"
}variable "compute_exists" {
  default = "1"
}variable "ComputePort" {
  default = "None"
}variable "ComputeMaster" {
  default = "1"
}variable "ComputeWorker" {
  default = "6"
}variable "ComputeClusterMasterCPUMax" {
  default = "3"
}variable "ComputeClusterMasterCPUMin" {
  default = "1"
}variable "ComputeClusterMasterMemMax" {
  default = "3"
}variable "ComputeClusterMasterMemMin" {
  default = "1"
}variable "ComputeClusterWorkerCPUMax" {
  default = "3"
}variable "ComputeClusterWorkerCPUMin" {
  default = "1"
}variable "ComputeClusterWorkerMemMax" {
  default = "3"
}variable "ComputeClusterWorkerMemMin" {
  default = "1"
}variable "Database" {
  default = "None"
}variable "DatabaseCopies" {
  default = "0"
}variable "DatabaseSize" {
  default = "0"
}variable "EC2num" {
  default = "0"
}variable "EC2Port" {
  default = "None"
}
