apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    presto: worker
  name: worker
spec:
  replicas: WORKER #1
  template:
    metadata:
      labels:
        presto: worker
    spec:
      containers:
      - env:
        - name: HTTP_SERVER_PORT
          value: "8080"
        - name: PRESTO_JVM_HEAP_SIZE
          value: "8"
        - name: PRESTO_MAX_MEMORY
          value: "10"
        - name: PRESTO_MAX_MEMORY_PER_NODE
          value: "1"
        - name : COORDINATOR
          value: "presto"
        image: johandry/presto
        livenessProbe:
          exec:
            command:
            - /etc/init.d/presto status | grep -q 'Running as'
          failureThreshold: 3
          periodSeconds: 300
          timeoutSeconds: 10
        name: worker
        ports:
        - containerPort: 8080
      restartPolicy: Always
