variable "InstanceType" {
  default = "t2.micro"
}variable "Nodes" {
  default = "4"
}variable "IngestionSystem" {
  default = "None"
}variable "Master" {
  default = "0"
}variable "Worker" {
  default = "0"
}variable "OpenPort" {
  default = "None"
}variable "MaximumCPU" {
  default = "0"
}variable "MinimumCPU" {
  default = "0"
}variable "MaximumMemory" {
  default = "0"
}variable "MinimumMemory" {
  default = "0"
}variable "MaximumCPU" {
  default = "0"
}variable "MinimumCPU" {
  default = "0"
}variable "MaximumMemory" {
  default = "0"
}variable "MinimumMemory" {
  default = "0"
}variable "ComputeCluster" {
  default = "spark"
}variable "OpenPort" {
  default = "None"
}variable "Master" {
  default = "1"
}variable "Worker" {
  default = "3"
}variable "MaximumCPU" {
  default = "100"
}variable "MinimumCPU" {
  default = "100"
}variable "MaximumMemory" {
  default = "100"
}variable "MinimumMemory" {
  default = "100"
}variable "MaximumCPU" {
  default = "100"
}variable "MinimumCPU" {
  default = "100"
}variable "MaximumMemory" {
  default = "100"
}variable "MinimumMemory" {
  default = "100"
}variable "KubernetesDatabase" {
  default = "None"
}variable "OpenPort" {
  default = "None"
}variable "databaseNumber" {
  default = "0"
}variable "databaseSize" {
  default = "0"
}variable "ExtraEC2" {
  default = "0"
}variable "ExtraEC2" {
  default = "None"
}variable "OpenPort" {
  default = "None"
}variable "KubeNodeType" {
  default = "t2.micro"
}variable "KubeNodes" {
  default = "3"
}variable "Ingestion" {
  default = "kafka"
}variable "OpenPort" {
  default = "None"
}variable "Master" {
  default = "1"
}variable "Worker" {
  default = "3"
}variable "IngestionMasterCPUMax" {
  default = "100"
}variable "IngestionMasterCPUMin" {
  default = "100"
}variable "IngestionMasterMemMax" {
  default = "100"
}variable "IngestionMasterMemMin" {
  default = "100"
}variable "IngestionWorkerCPUMax" {
  default = "100"
}variable "IngestionWorkerCPUMin" {
  default = "100"
}variable "IngestionWorkerMemMax" {
  default = "100"
}variable "IngestionWorkerMemMin" {
  default = "100"
}variable "Compute" {
  default = "None"
}variable "Master" {
  default = "0"
}variable "Worker" {
  default = "0"
}variable "OpenPort" {
  default = "None"
}variable "ComputeCPUMax" {
  default = "0"
}variable "ComputeCPUMin" {
  default = "0"
}variable "ComputeMemMax" {
  default = "0"
}variable "ComputeMemMin" {
  default = "0"
}variable "ComputeCPUMax" {
  default = "0"
}variable "ComputeCPUMin" {
  default = "0"
}variable "ComputeMemMax" {
  default = "0"
}variable "ComputeMemMin" {
  default = "0"
}variable "Database" {
  default = "None"
}variable "OpenPort" {
  default = "None"
}variable "DatabaseCopies" {
  default = "0"
}variable "DatabaseSize" {
  default = "0"
}variable "EC2num" {
  default = "0"
}variable "EC2num" {
  default = "None"
}variable "OpenPort" {
  default = "None"
}